import { writeFileSync } from "node:fs";
import type { MapId, RadarLayerId } from "../../src/shared/maps.ts";
import type { MapPoint } from "../../src/shared/types.ts";
import type { ViewAngle, WorldPosition } from "../../src/shared/radarCoordinates.ts";
import type { QuestionDifficulty } from "../../src/shared/questionDifficulty.ts";

export interface ManifestQuestion {
  id: string;
  imageAssetId: string;
  correctMapId: MapId;
  correctLayerId: RadarLayerId;
  difficulty: QuestionDifficulty;
  correctPoint: MapPoint;
  automaticPoint: MapPoint;
  worldPosition: WorldPosition;
  viewAngle?: ViewAngle;
  coordinateSource: "world-conversion" | "manual-override";
}

export function writeGeneratedManifest(path: string, questions: readonly ManifestQuestion[]): void {
  const serialized = JSON.stringify(questions, null, 2);
  writeFileSync(path, `import type { LegacyManifestQuestion } from "./questions";\n\n// Generated by the real-question import tools. Do not hand-edit.\nexport const QUESTION_MANIFEST = ${serialized} as const satisfies readonly LegacyManifestQuestion[];\n`);
}
