import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { RadarProviderResult } from "../../src/content/radarProvider";
import { MAP_IDS, type MapId } from "../../src/shared/maps";
import type { MapOverview } from "../../src/shared/radarCoordinates";

export const projectRoot = resolve(import.meta.dirname, "..", "..");
export const generatedRoot = join(projectRoot, "content", "generated");
export const radarRoot = join(generatedRoot, "radars");
export const publicDevAssetsRoot = join(projectRoot, "public", "__dev_assets__");
export const runtimeOverviewPath = join(projectRoot, "src", "shared", "mapOverviews.generated.ts");

function runtimeOverview(overview: MapOverview, sourceBuildId: string): MapOverview {
  return {
    mapId: overview.mapId,
    sourceName: overview.sourceName,
    posX: overview.posX,
    posY: overview.posY,
    scale: overview.scale,
    rotate: overview.rotate,
    zoom: overview.zoom,
    layers: overview.layers.map((layer) => ({ ...layer })),
    extractedAt: "generated-by-radar-sync",
    sourceBuildId,
  };
}

export function writeRuntimeOverviewRegistry(result: RadarProviderResult): string {
  const maps = Object.fromEntries(MAP_IDS.map((mapId) => {
    const overview = result.maps[mapId];
    if (!overview) throw new Error(`RUNTIME_OVERVIEW_MISSING ${mapId}`);
    return [mapId, runtimeOverview(overview, result.sourceBuildId)];
  })) as Record<MapId, MapOverview>;
  const source = `// Generated by npm run radar:sync. Do not edit manually.\n`
    + `import type { MapId } from "./maps.ts";\n`
    + `import type { MapOverview } from "./radarCoordinates.ts";\n\n`
    + `export const MAP_OVERVIEWS: Readonly<Record<MapId, MapOverview>> = ${JSON.stringify(maps, null, 2)};\n\n`
    + `export function getMapOverview(mapId: MapId): MapOverview {\n`
    + `  return MAP_OVERVIEWS[mapId];\n`
    + `}\n`;
  writeFileSync(runtimeOverviewPath, source);
  return runtimeOverviewPath;
}

export function writeRadarRegistry(result: RadarProviderResult): string {
  mkdirSync(generatedRoot, { recursive: true });
  const path = join(generatedRoot, "map-overviews.json");
  writeFileSync(path, `${JSON.stringify({
    provider: result.provider,
    providerUrl: result.providerUrl,
    sourceBuildId: result.sourceBuildId,
    syncedAt: new Date().toISOString(),
    artifacts: result.artifacts,
    overviews: result.overviews,
    maps: result.maps,
  }, null, 2)}\n`);
  return path;
}
