// Generated by npm run radar:sync. Do not edit manually.
import type { MapId } from "./maps.ts";
import type { MapOverview } from "./radarCoordinates.ts";

export const MAP_OVERVIEWS: Readonly<Record<MapId, MapOverview>> = {
  "mirage": {
    "mapId": "mirage",
    "sourceName": "de_mirage",
    "posX": -3230,
    "posY": 1713,
    "scale": 5,
    "rotate": 0,
    "zoom": 0,
    "layers": [
      {
        "id": "main",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  },
  "inferno": {
    "mapId": "inferno",
    "sourceName": "de_inferno",
    "posX": -2087,
    "posY": 3870,
    "scale": 4.9,
    "rotate": 0,
    "zoom": 0,
    "layers": [
      {
        "id": "main",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  },
  "ancient": {
    "mapId": "ancient",
    "sourceName": "de_ancient",
    "posX": -2953,
    "posY": 2164,
    "scale": 5,
    "rotate": 0,
    "zoom": 0,
    "layers": [
      {
        "id": "main",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  },
  "nuke": {
    "mapId": "nuke",
    "sourceName": "de_nuke",
    "posX": -3453,
    "posY": 2887,
    "scale": 7,
    "rotate": 0,
    "zoom": 0,
    "layers": [
      {
        "id": "upper",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024,
        "altitudeMin": -495,
        "altitudeMax": 10000
      },
      {
        "id": "lower",
        "sourceSectionName": "lower",
        "radarWidth": 1024,
        "radarHeight": 1024,
        "altitudeMin": -10000,
        "altitudeMax": -495
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  },
  "anubis": {
    "mapId": "anubis",
    "sourceName": "de_anubis",
    "posX": -2796,
    "posY": 3328,
    "scale": 5.22,
    "rotate": 0,
    "zoom": 0,
    "layers": [
      {
        "id": "main",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  },
  "dust2": {
    "mapId": "dust2",
    "sourceName": "de_dust2",
    "posX": -2476,
    "posY": 3239,
    "scale": 4.4,
    "rotate": 1,
    "zoom": 1.1,
    "layers": [
      {
        "id": "main",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  },
  "train": {
    "mapId": "train",
    "sourceName": "de_train",
    "posX": -2308,
    "posY": 2078,
    "scale": 4.082077,
    "rotate": 0,
    "zoom": 0,
    "layers": [
      {
        "id": "upper",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024,
        "altitudeMin": -50,
        "altitudeMax": 20000
      },
      {
        "id": "lower",
        "sourceSectionName": "lower",
        "radarWidth": 1024,
        "radarHeight": 1024,
        "altitudeMin": -5000,
        "altitudeMax": -50
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  },
  "overpass": {
    "mapId": "overpass",
    "sourceName": "de_overpass",
    "posX": -4831,
    "posY": 1781,
    "scale": 5.2,
    "rotate": 0,
    "zoom": 0,
    "layers": [
      {
        "id": "main",
        "sourceSectionName": "default",
        "radarWidth": 1024,
        "radarHeight": 1024
      }
    ],
    "extractedAt": "generated-by-radar-sync",
    "sourceBuildId": "github-index:94042f894a9252ae"
  }
};

export function getMapOverview(mapId: MapId): MapOverview {
  return MAP_OVERVIEWS[mapId];
}
