import type { MapId, RadarLayerId } from "../../shared/maps";
import type { MapPoint } from "../../shared/types";
import type { PublicQuestion } from "../../shared/types";
import type { ViewAngle, WorldPosition } from "../../shared/radarCoordinates";
import { QUESTION_MANIFEST } from "./questionManifest.generated";

export interface Question {
  id: string;
  imageAssetId: string;
  correctMapId: MapId;
  correctLayerId: RadarLayerId;
  correctPoint: MapPoint;
  worldPosition: WorldPosition;
  viewAngle?: ViewAngle;
  coordinateSource: "world-conversion" | "manual-override";
}

// Generated by npm run question:import. This module is Worker-only.
export const QUESTIONS: readonly Question[] = QUESTION_MANIFEST;

export function getQuestion(questionId: string): Question {
  const question = QUESTIONS.find((candidate) => candidate.id === questionId);
  if (!question) throw new Error(`Unknown question: ${questionId}`);
  return question;
}

export function toPublicQuestion(question: Question): PublicQuestion {
  return { questionId: question.id, imageUrl: `/media/questions/${question.imageAssetId}` };
}

export function shuffledQuestionIds(count: number): string[] {
  const ids = QUESTIONS.map((question) => question.id);
  for (let index = ids.length - 1; index > 0; index -= 1) {
    const random = crypto.getRandomValues(new Uint32Array(1))[0] / 2 ** 32;
    const target = Math.floor(random * (index + 1));
    [ids[index], ids[target]] = [ids[target], ids[index]];
  }
  return ids.slice(0, count);
}
